services:
  grill-gauge-api:
    image: grill-gauge-api:latest
    container_name: grill-gauge-api
    ports:
      - "8080:8080"
    environment:
      - INT_CA_KEY_PASSPHRASE=${INT_CA_KEY_PASSPHRASE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ~/intermediateCA:/app/CA:ro
    # depends_on:
    #   - grill-gauge-db

  # grill-gauge-db:
  #   image: postgres:15
  #   container_name: grill-gauge-db
  #   environment:
  #     - POSTGRES_USER=grillgauge
  #     - POSTGRES_PASSWORD=grillgaugepassword
  #     - POSTGRES_DB=grillgauge
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - grill-gauge-db-data:/var/lib/postgresql/data